### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by robmoore-i** [blajos/libgtop11dotnet#1]
Hi,

How do we build this? We notice there is a configure and some make stuff.

We are using ARM architecture (Raspberry pi).

Thanks very much,

Rob and Natalia

**Comment by blajos** [comment]
Hi,

Actually I have no idea (it was a very long time ago.) The original source is this: https://launchpad.net/~arnaud-morin/+archive/ubuntu/gemalto

If you can satisfy the build-deps somehow, and run dpkg-buildpackage, then it should work.

Regards,
Lajos
